"""create generalized core tables

Revision ID: 8c7f485b771f
Revises: a8cb3a68743f
Create Date: 2026-09-17 02:52:05.303132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7f485b771f'
down_revision: Union[str, Sequence[str], None] = 'a8cb3a68743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_created_by_user_id'), 'workflow_templates', ['created_by_user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('workflow_template_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_agent_id'), 'campaigns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_campaigns_created_by_user_id'), 'campaigns', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workflow_template_id'), 'campaigns', ['workflow_template_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('workflow_step', sa.String(length=255), nullable=True),
    sa.Column('step_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'READY_FOR_ACTION', name='workflowstepstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_campaign_id'), 'candidates', ['campaign_id'], unique=False)
    op.create_table('call_screenings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmatched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_screenings_campaign_id'), 'call_screenings', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_screenings_candidate_id'), 'call_screenings', ['candidate_id'], unique=False)
    op.create_table('document_screenings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmatched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_screenings_campaign_id'), 'document_screenings', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_document_screenings_candidate_id'), 'document_screenings', ['candidate_id'], unique=False)
    op.create_table('workflow_event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_event_logs_campaign_id'), 'workflow_event_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_workflow_event_logs_candidate_id'), 'workflow_event_logs', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_event_logs_candidate_id'), table_name='workflow_event_logs')
    op.drop_index(op.f('ix_workflow_event_logs_campaign_id'), table_name='workflow_event_logs')
    op.drop_table('workflow_event_logs')
    op.drop_index(op.f('ix_document_screenings_candidate_id'), table_name='document_screenings')
    op.drop_index(op.f('ix_document_screenings_campaign_id'), table_name='document_screenings')
    op.drop_table('document_screenings')
    op.drop_index(op.f('ix_call_screenings_candidate_id'), table_name='call_screenings')
    op.drop_index(op.f('ix_call_screenings_campaign_id'), table_name='call_screenings')
    op.drop_table('call_screenings')
    op.drop_index(op.f('ix_candidates_campaign_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_campaigns_workflow_template_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_by_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_agent_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_workflow_templates_created_by_user_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
