"""create_hiring_campaigns_and_candidates_tables

Revision ID: 947d1e79faa5
Revises: a8cb3a68743f
Create Date: 2026-09-12 20:14:05.122354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947d1e79faa5'
down_revision: Union[str, Sequence[str], None] = 'a8cb3a68743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiring_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', name='employmenttype'), nullable=False),
    sa.Column('role_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCREENING', 'PAUSED', 'SCREENED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('job_description_raw', sa.Text(), nullable=False),
    sa.Column('jd_extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_campaigns_user_id'), 'hiring_campaigns', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_resume_url', sa.Text(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESUME_PARSED', 'RESUME_SCREENED', 'CALL_SCHEDULED', 'CALL_COMPLETED', 'REJECTED', 'PASSED', name='candidatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['hiring_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_campaign_id'), 'candidates', ['campaign_id'], unique=False)
    op.create_table('resume_screenings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('one_line_summary', sa.String(length=512), nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_screenings_candidate_id'), 'resume_screenings', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_screenings_candidate_id'), table_name='resume_screenings')
    op.drop_table('resume_screenings')
    op.drop_index(op.f('ix_candidates_campaign_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_hiring_campaigns_user_id'), table_name='hiring_campaigns')
    op.drop_table('hiring_campaigns')
    # ### end Alembic commands ###
