"""create agent domain tables

Revision ID: a8cb3a68743f
Revises: c0dd42deef7f
Create Date: 2026-09-11 03:11:55.815767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cb3a68743f'
down_revision: Union[str, Sequence[str], None] = 'c0dd42deef7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_style', sa.Enum('FRIENDLY_CONVERSATIONAL', 'CONVERSATIONAL', 'FORMAL', 'PROFESSIONAL', name='conversationstyle', native_enum=False), nullable=False),
    sa.Column('languages', sa.Enum('ENGLISH', 'ENGLISH_HINDI', 'ENGLISH_HINDI_MARATHI', name='languagepreference', native_enum=False), nullable=False),
    sa.Column('voice', sa.Enum('WARM_CLEAR', 'CLEAR_CONFIDENT', 'NATURAL_CLEAR', 'SOFT_PROFESSIONAL', name='voicepreference', native_enum=False), nullable=False),
    sa.Column('interview_instruction', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conversation_style', sa.Enum('FRIENDLY_CONVERSATIONAL', 'CONVERSATIONAL', 'FORMAL', 'PROFESSIONAL', name='conversationstyle', native_enum=False), nullable=False),
    sa.Column('languages', sa.Enum('ENGLISH', 'ENGLISH_HINDI', 'ENGLISH_HINDI_MARATHI', name='languagepreference', native_enum=False), nullable=False),
    sa.Column('voice', sa.Enum('WARM_CLEAR', 'CLEAR_CONFIDENT', 'NATURAL_CLEAR', 'SOFT_PROFESSIONAL', name='voicepreference', native_enum=False), nullable=False),
    sa.Column('interview_instruction', sa.String(length=2000), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_created_by_user_id'), 'agents', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_created_by_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agent_presets')
    # ### end Alembic commands ###
