"""rename campaign extracted_fields to required_fields and add candidate extracted_fields

Revision ID: cc6f991f975a
Revises: 8c7f485b771f
Create Date: 2026-09-17 13:00:03.154650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc6f991f975a'
down_revision: Union[str, Sequence[str], None] = '8c7f485b771f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('campaigns', 'extracted_fields')
    op.add_column('candidates', sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'extracted_fields')
    op.add_column('campaigns', sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'required_fields')
    # ### end Alembic commands ###
