"""add_is_summarised_to_chat_messages

Revision ID: e9a5b544f0b1
Revises: 7e274254bcc2
Create Date: 2026-10-06 02:37:45.389708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a5b544f0b1'
down_revision: Union[str, Sequence[str], None] = '7e274254bcc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_summarised', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_chat_messages_is_summarised'), 'chat_messages', ['is_summarised'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_is_summarised'), table_name='chat_messages')
    op.drop_column('chat_messages', 'is_summarised')
    # ### end Alembic commands ###
